export const SEND_NOTIFICATION_REQUEST = 'SEND_NOTIFICATION_REQUEST';
export const SEND_NOTIFICATION_SUCCESS = 'SEND_NOTIFICATION_SUCCESS';
export const SEND_NOTIFICATION_FAILURE = 'SEND_NOTIFICATION_FAILURE';

export const FETCH_ANNOUNCEMENT_LIST_REQUEST = 'FETCH_ANNOUNCEMENT_LIST_REQUEST';
export const FETCH_ANNOUNCEMENT_LIST_SUCCESS = 'FETCH_ANNOUNCEMENT_LIST_SUCCESS';
export const FETCH_ANNOUNCEMENT_LIST_FAILURE = 'FETCH_ANNOUNCEMENT_LIST_FAILURE';

export const DELETE_ANNOUNCEMENT_REQUEST = 'DELETE_ANNOUNCEMENT_REQUEST';
export const DELETE_ANNOUNCEMENT_SUCCESS = 'DELETE_ANNOUNCEMENT_SUCCESS';
export const DELETE_ANNOUNCEMENT_FAILURE = 'DELETE_ANNOUNCEMENT_FAILURE';
