export const GET_ALL_BUSINESSES_REQUEST = "GET_ALL_BUSINESSES_REQUEST";
export const GET_ALL_BUSINESSES_SUCCESS = "GET_ALL_BUSINESSES_SUCCESS";
export const GET_ALL_BUSINESSES_FAILURE = "GET_ALL_BUSINESSES_FAILURE";

export const UPDATE_BUSINESS_REQUEST = "UPDATE_BUSINESS_REQUEST";
export const UPDATE_BUSINESS_SUCCESS = "UPDATE_BUSINESS_SUCCESS";
export const UPDATE_BUSINESS_FAILURE = "UPDATE_BUSINESS_FAILURE";

export const DELETE_BUSINESS_REQUEST = "DELETE_BUSINESS_REQUEST";
export const DELETE_BUSINESS_SUCCESS = "DELETE_BUSINESS_SUCCESS";
export const DELETE_BUSINESS_FAILURE = "DELETE_BUSINESS_FAILURE";

export const GET_BUSINESS = "GET_BUSINESS";

export const SET_GLOBAL_BUSINESS_WALL_LIMIT_REQUEST = "SET_GLOBAL_BUSINESS_WALL_LIMIT_REQUEST";
export const SET_GLOBAL_BUSINESS_WALL_LIMIT_SUCCESS = "SET_GLOBAL_BUSINESS_WALL_LIMIT_SUCCESS";
export const SET_GLOBAL_BUSINESS_WALL_LIMIT_FAILURE = "SET_GLOBAL_BUSINESS_WALL_LIMIT_FAILURE";

export const SET_BUSINESS_WALL_LIMIT_REQUEST = "SET_BUSINESS_WALL_LIMIT_REQUEST";
export const SET_BUSINESS_WALL_LIMIT_SUCCESS = "SET_BUSINESS_WALL_LIMIT_SUCCESS";
export const SET_BUSINESS_WALL_LIMIT_FAILURE = "SET_BUSINESS_WALL_LIMIT_FAILURE";

