export const GET_ALL_FREQUENCY_REQUEST = "GET_ALL_FREQUENCY_REQUEST";
export const GET_ALL_FREQUENCY_SUCCESS = "GET_ALL_FREQUENCY_SUCCESS";
export const GET_ALL_FREQUENCY_FAIL = "GET_ALL_FREQUENCY_FAIL";

export const CREATE_FREQUENCY_REQUEST = "CREATE_FREQUENCY_REQUEST";
export const CREATE_FREQUENCY_SUCCESS = "CREATE_FREQUENCY_SUCCESS";
export const CREATE_FREQUENCY_FAIL = "CREATE_FREQUENCY_FAIL";

export const DELETE_FREQUENCY_REQUEST = "DELETE_FREQUENCY_REQUEST";
export const DELETE_FREQUENCY_SUCCESS = "DELETE_FREQUENCY_SUCCESS";
export const DELETE_FREQUENCY_FAIL = "DELETE_FREQUENCY_FAIL";

