

export const FETCH_NOTES_REQUEST = "FETCH_NOTES_REQUEST";
export const FETCH_NOTES_SUCCESS = "FETCH_NOTES_SUCCESS";
export const FETCH_NOTES_FAILURE = "FETCH_NOTES_FAILURE";

export const GET_NOTE = "GET_NOTE";


export const DELETE_NOTE_REQUEST = 'DELETE_NOTE_REQUEST';
export const DELETE_NOTE_SUCCESS = 'DELETE_NOTE_SUCCESS';
export const DELETE_NOTE_FAILURE = 'DELETE_NOTE_FAILURE';

export const NOTE_DETAILS_REQUEST = 'NOTE_DETAILS_REQUEST';
export const NOTE_DETAILS_SUCCESS = 'NOTE_DETAILS_SUCCESS';
export const NOTE_DETAILS_FAILURE = 'NOTE_DETAILS_FAILURE';

export const UPDATE_NOTE_REQUEST = 'UPDATE_NOTE_REQUEST';
export const UPDATE_NOTE_SUCCESS = 'UPDATE_NOTE_SUCCESS';
export const UPDATE_NOTE_FAILURE = 'UPDATE_NOTE_FAILURE';


export const SET_USER_NOTE_LIMIT_REQUEST = 'SET_USER_NOTE_LIMIT_REQUEST';
export const SET_USER_NOTE_LIMIT_SUCCESS = 'SET_USER_NOTE_LIMIT_SUCCESS';
export const SET_USER_NOTE_LIMIT_FAILURE = 'SET_USER_NOTE_LIMIT_FAILURE';


export const SET_GLOBAL_NOTE_LIMIT_REQUEST = 'SET_GLOBAL_NOTE_LIMIT_REQUEST';
export const SET_GLOBAL_NOTE_LIMIT_SUCCESS = 'SET_GLOBAL_NOTE_LIMIT_SUCCESS';
export const SET_GLOBAL_NOTE_LIMIT_FAILURE = 'SET_GLOBAL_NOTE_LIMIT_FAILURE';

