export const FETCH_REMINDERS_REQUEST = "FETCH_REMINDERS_REQUEST";
export const FETCH_REMINDERS_SUCCESS = "FETCH_REMINDERS_SUCCESS";
export const FETCH_REMINDERS_FAILURE = "FETCH_REMINDERS_FAILURE";

export const GET_REMINDER = "GET_REMINDER";


export const SET_USER_REMINDER_LIMIT_REQUEST = 'SET_USER_REMINDER_LIMIT_REQUEST';
export const SET_USER_REMINDER_LIMIT_SUCCESS = 'SET_USER_REMINDER_LIMIT_SUCCESS';
export const SET_USER_REMINDER_LIMIT_FAILURE = 'SET_USER_REMINDER_LIMIT_FAILURE';


export const SET_GLOBAL_REMINDER_LIMIT_REQUEST = "SET_GLOBAL_REMINDER_LIMIT_REQUEST";
export const SET_GLOBAL_REMINDER_LIMIT_SUCCESS = "SET_GLOBAL_REMINDER_LIMIT_SUCCESS";
export const SET_GLOBAL_REMINDER_LIMIT_FAILURE = "SET_GLOBAL_REMINDER_LIMIT_FAILURE";

export const REMINDER_DETAILS_REQUEST = "REMINDER_DETAILS_REQUEST";
export const REMINDER_DETAILS_SUCCESS = "REMINDER_DETAILS_SUCCESS";
export const REMINDER_DETAILS_FAILURE = "REMINDER_DETAILS_FAILURE";

export const DELETE_REMINDER_REQUEST = "DELETE_REMINDER_REQUEST";
export const DELETE_REMINDER_SUCCESS = "DELETE_REMINDER_SUCCESS";
export const DELETE_REMINDER_FAILURE = "DELETE_REMINDER_FAILURE";

export const UPDATE_REMINDER_REQUEST = "UPDATE_REMINDER_REQUEST";
export const UPDATE_REMINDER_SUCCESS = "UPDATE_REMINDER_SUCCESS";
export const UPDATE_REMINDER_FAILURE = "UPDATE_REMINDER_FAILURE";



