export const GET_ALL_REPORTS_REQUEST = "GET_ALL_REPORTS_REQUEST";
export const GET_ALL_REPORTS_SUCCESS = "GET_ALL_REPORTS_SUCCESS";
export const GET_ALL_REPORTS_FAIL = "GET_ALL_REPORTS_FAIL";

export const REVIEW_REPORT_REQUEST = "REVIEW_REPORT_REQUEST";
export const REVIEW_REPORT_SUCCESS = "REVIEW_REPORT_SUCCESS";
export const REVIEW_REPORT_FAIL = "REVIEW_REPORT_FAIL";