export const FETCH_DATA_REQUEST = "FETCH_DATA_REQUEST";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_FAILURE = "FETCH_DATA_FAILURE";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE";

export const BAN_USER_REQUEST = "BAN_USER_REQUEST";
export const BAN_USER_SUCCESS = "BAN_USER_SUCCESS";
export const BAN_USER_FAILURE = "BAN_USER_FAILURE";

export const UNBAN_USER_REQUEST = "UNBAN_USER_REQUEST";
export const UNBAN_USER_SUCCESS = "UNBAN_USER_SUCCESS";
export const UNBAN_USER_FAILURE = "UNBAN_USER_FAILURE";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAILURE = "USER_DETAILS_FAILURE";

export const ASSIGN_MODERATOR_REQUEST = 'ASSIGN_MODERATOR_REQUEST';
export const ASSIGN_MODERATOR_SUCCESS = 'ASSIGN_MODERATOR_SUCCESS';
export const ASSIGN_MODERATOR_FAILURE = 'ASSIGN_MODERATOR_FAILURE';

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';

export const ALL_ACTIVITY_LOGS_REQUEST = "ALL_ACTIVITY_LOGS_REQUEST";
export const ALL_ACTIVITY_LOGS_SUCCESS = "ALL_ACTIVITY_LOGS_SUCCESS";
export const ALL_ACTIVITY_LOGS_FAIL = "ALL_ACTIVITY_LOGS_FAIL";

export const SET_USER_POST_LIMIT_REQUEST = "SET_USER_POST_LIMIT_REQUEST";
export const SET_USER_POST_LIMIT_SUCCESS = "SET_USER_POST_LIMIT_SUCCESS";
export const SET_USER_POST_LIMIT_FAILURE = "SET_USER_POST_LIMIT_FAILURE";

export const GET_ACTIVE_BUSINESS_USERS_REQUEST = "GET_ACTIVE_BUSINESS_USERS_REQUEST";
export const GET_ACTIVE_BUSINESS_USERS_SUCCESS = "GET_ACTIVE_BUSINESS_USERS_SUCCESS";
export const GET_ACTIVE_BUSINESS_USERS_FAIL = "GET_ACTIVE_BUSINESS_USERS_FAIL";
