export const FETCH_WALL_LIST_REQUEST = 'FETCH_WALL_LIST_REQUEST';
export const FETCH_WALL_LIST_SUCCESS = 'FETCH_WALL_LIST_SUCCESS';
export const FETCH_WALL_LIST_FAILURE = 'FETCH_WALL_LIST_FAILURE';

export const DELETE_WALL_REQUEST = 'DELETE_WALL_REQUEST';
export const DELETE_WALL_SUCCESS = 'DELETE_WALL_SUCCESS';
export const DELETE_WALL_FAILURE = 'DELETE_WALL_FAILURE';

export const GET_WALL = 'GET_WALL';

export const DELETE_WALL_FILE_SUCCESS = 'DELETE_WALL_FILE_SUCCESS';

export const UPDATE_WALL_FILE_REQUEST = 'UPDATE_WALL_FILE_REQUEST';
export const UPDATE_WALL_FILE_SUCCESS = 'UPDATE_WALL_FILE_SUCCESS';
export const UPDATE_WALL_FILE_FAILURE = 'UPDATE_WALL_FILE_FAILURE';

export const SET_GLOBAL_WALL_LIMIT_REQUEST = 'SET_GLOBAL_WALL_LIMIT_REQUEST';
export const SET_GLOBAL_WALL_LIMIT_SUCCESS = 'SET_GLOBAL_WALL_LIMIT_SUCCESS';
export const SET_GLOBAL_WALL_LIMIT_FAILURE = 'SET_GLOBAL_WALL_LIMIT_FAILURE';
